import 'package:flutter/material.dart';

class Train{
  final String id;
  final String name;
  final String from_location;
  final String to_location;
  final TimeOfDay departure_time;
  final TimeOfDay arrival_time;
  final DateTime date;
  final String duration;
  final String distance;

  const Train(
      this.id,
      this.name,
      this.from_location,
      this.to_location,
      this.departure_time,
      this.arrival_time,
      this.date,
      this.duration,
      this.distance);
}

List<Map<String, dynamic>> dummyTrainData = [
  {
    'trainNumber': '001',
    'trainName': 'Colombo to Galle Express',
    'startStation': 'Colombo Fort',
    'endStation': 'Galle',
    'startTime': '08:00 AM',
    'endTime': '10:30 AM',
  },
  {
    'trainNumber': '002',
    'trainName': 'Galle to Colombo Express',
    'startStation': 'Galle',
    'endStation': 'Colombo Fort',
    'startTime': '04:30 PM',
    'endTime': '07:00 PM',
  },
  {
    'trainNumber': '003',
    'trainName': 'Colombo to Kandy Intercity',
    'startStation': 'Colombo Fort',
    'endStation': 'Kandy',
    'startTime': '09:15 AM',
    'endTime': '12:30 PM',
  },
  {
    'trainNumber': '004',
    'trainName': 'Kandy to Colombo Intercity',
    'startStation': 'Kandy',
    'endStation': 'Colombo Fort',
    'startTime': '10:00 AM',
    'endTime': '01:15 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '005',
    'trainName': 'Colombo to Badulla Express',
    'startStation': 'Colombo Fort',
    'endStation': 'Badulla',
    'startTime': '06:45 AM',
    'endTime': '06:30 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '006',
    'trainName': 'Badulla to Colombo Express',
    'startStation': 'Badulla',
    'endStation': 'Colombo Fort',
    'startTime': '07:30 AM',
    'endTime': '07:15 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '007',
    'trainName': 'Colombo to Jaffna Intercity',
    'startStation': 'Colombo Fort',
    'endStation': 'Jaffna',
    'startTime': '06:30 AM',
    'endTime': '02:45 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '008',
    'trainName': 'Jaffna to Colombo Intercity',
    'startStation': 'Jaffna',
    'endStation': 'Colombo Fort',
    'startTime': '03:30 PM',
    'endTime': '11:45 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '009',
    'trainName': 'Colombo to Matara Express',
    'startStation': 'Colombo Fort',
    'endStation': 'Matara',
    'startTime': '08:15 AM',
    'endTime': '10:45 AM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '010',
    'trainName': 'Matara to Colombo Express',
    'startStation': 'Matara',
    'endStation': 'Colombo Fort',
    'startTime': '02:30 PM',
    'endTime': '05:00 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '011',
    'trainName': 'Colombo to Anuradhapura Express',
    'startStation': 'Colombo Fort',
    'endStation': 'Anuradhapura',
    'startTime': '05:30 AM',
    'endTime': '10:15 AM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '012',
    'trainName': 'Anuradhapura to Colombo Express',
    'startStation': 'Anuradhapura',
    'endStation': 'Colombo Fort',
    'startTime': '11:00 AM',
    'endTime': '03:45 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '013',
    'trainName': 'Colombo to Batticaloa Express',
    'startStation': 'Colombo Fort',
    'endStation': 'Batticaloa',
    'startTime': '07:00 AM',
    'endTime': '05:30 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '014',
    'trainName': 'Batticaloa to Colombo Express',
    'startStation': 'Batticaloa',
    'endStation': 'Colombo Fort',
    'startTime': '06:30 AM',
    'endTime': '05:00 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '015',
    'trainName': 'Colombo to Trincomalee Express',
    'startStation': 'Colombo Fort',
    'endStation': 'Trincomalee',
    'startTime': '07:15 AM',
    'endTime': '03:45 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '016',
    'trainName': 'Trincomalee to Colombo Express',
    'startStation': 'Trincomalee',
    'endStation': 'Colombo Fort',
    'startTime': '04:30 PM',
    'endTime': '01:00 AM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '017',
    'trainName': 'Colombo to Galle Express',
    'startStation': 'Colombo Fort',
    'endStation': 'Galle',
    'startTime': '07:30 AM',
    'endTime': '09:15 AM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '018',
    'trainName': 'Galle to Colombo Express',
    'startStation': 'Galle',
    'endStation': 'Colombo Fort',
    'startTime': '04:00 PM',
    'endTime': '05:45 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '019',
    'trainName': 'Colombo to Kandy Intercity',
    'startStation': 'Colombo Fort',
    'endStation': 'Kandy',
    'startTime': '05:45 AM',
    'endTime': '09:00 AM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '020',
    'trainName': 'Kandy to Colombo Intercity',
    'startStation': 'Kandy',
    'endStation': 'Colombo Fort',
    'startTime': '04:30 PM',
    'endTime': '07:45 PM',
    'trainType': 'weekday',
  },
  {
    'trainNumber': '021',
    'trainName': 'Colombo to Galle Express',
    'startStation': 'Colombo Fort',
    'endStation': 'Galle',
    'startTime': '06:00 AM',
    'endTime': '07:45 AM',
    'trainType': 'weekend',
  },
  {
    'trainNumber': '022',
    'trainName': 'Galle to Colombo Express',
    'startStation': 'Galle',
    'endStation': 'Colombo Fort',
    'startTime': '05:30 PM',
    'endTime': '07:15 PM',
    'trainType': 'weekend',
  },
  {
    'trainNumber': '023',
    'trainName': 'Colombo to Kandy Intercity',
    'startStation': 'Colombo Fort',
    'endStation': 'Kandy',
    'startTime': '06:45 AM',
    'endTime': '09:30 AM',
    'trainType': 'weekend',
  },
  {
    'trainNumber': '024',
    'trainName': 'Kandy to Colombo Intercity',
    'startStation': 'Kandy',
    'endStation': 'Colombo Fort',
    'startTime': '05:15 PM',
    'endTime': '07:45 PM',
    'trainType': 'weekend',
  },
  {
    'trainNumber': '025',
    'trainName': 'Colombo to Badulla Express',
    'startStation': 'Colombo Fort',
    'endStation': 'Badulla',
    'startTime': '07:30 AM',
    'endTime': '07:15 PM',
    'trainType': 'special',
  },
  {
    'trainNumber': '026',
    'trainName': 'Badulla to Colombo Express',
    'startStation': 'Badulla',
    'endStation': 'Colombo Fort',
    'startTime': '06:30 AM',
    'endTime': '06:15 PM',
    'trainType': 'special',
  },
  {
    'trainNumber': '027',
    'trainName': 'Colombo to Jaffna Intercity',
    'startStation': 'Colombo Fort',
    'endStation': 'Jaffna',
    'startTime': '06:00 AM',
    'endTime': '01:15 PM',
    'trainType': 'special',
  },
  {
    'trainNumber': '028',
    'trainName': 'Jaffna to Colombo Intercity',
    'startStation': 'Jaffna',
    'endStation': 'Colombo Fort',
    'startTime': '03:00 PM',
    'endTime': '10:15 PM',
    'trainType': 'special',
  },
  {
    'trainNumber': '029',
    'trainName': 'Colombo to Matara Express',
    'startStation': 'Colombo Fort',
    'endStation': 'Matara',
    'startTime': '08:00 AM',
    'endTime': '10:30 AM',
    'trainType': 'special',
  },
  {
    'trainNumber': '030',
    'trainName': 'Matara to Colombo Express',
    'startStation': 'Matara',
    'endStation': 'Colombo Fort',
    'startTime': '02:00 PM',
    'endTime': '04:30 PM',
    'trainType': 'special',
  },
];
