// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArKGpMFAywYK8xFToHBjNyjxMfGsFysoU',
    appId: '1:570513993670:web:70aed728564ca171200cc7',
    messagingSenderId: '570513993670',
    projectId: 'railway-ticketing-system',
    authDomain: 'railway-ticketing-system.firebaseapp.com',
    databaseURL: 'https://railway-ticketing-system-default-rtdb.firebaseio.com',
    storageBucket: 'railway-ticketing-system.appspot.com',
    measurementId: 'G-J2X84MHNGE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcSJtujJ91fE4PLbQ0gKIj4RJV7_yhHUg',
    appId: '1:570513993670:android:177d32936a24b3f0200cc7',
    messagingSenderId: '570513993670',
    projectId: 'railway-ticketing-system',
    databaseURL: 'https://railway-ticketing-system-default-rtdb.firebaseio.com',
    storageBucket: 'railway-ticketing-system.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnjw3efFQSLCrzXfN5Ir-Ii3AsXQDii98',
    appId: '1:570513993670:ios:2b6ed765c755e2f0200cc7',
    messagingSenderId: '570513993670',
    projectId: 'railway-ticketing-system',
    databaseURL: 'https://railway-ticketing-system-default-rtdb.firebaseio.com',
    storageBucket: 'railway-ticketing-system.appspot.com',
    iosClientId: '570513993670-2i407jeadhs8abjr5rb7lqqbg96cnsas.apps.googleusercontent.com',
    iosBundleId: 'com.example.railwayTicketing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnjw3efFQSLCrzXfN5Ir-Ii3AsXQDii98',
    appId: '1:570513993670:ios:2b6ed765c755e2f0200cc7',
    messagingSenderId: '570513993670',
    projectId: 'railway-ticketing-system',
    databaseURL: 'https://railway-ticketing-system-default-rtdb.firebaseio.com',
    storageBucket: 'railway-ticketing-system.appspot.com',
    iosClientId: '570513993670-2i407jeadhs8abjr5rb7lqqbg96cnsas.apps.googleusercontent.com',
    iosBundleId: 'com.example.railwayTicketing',
  );
}
